# Error handling
## Errors

By now, we have seen several pieces of code that have failed to run. In that case, Python does not only raise an error, but also specifies what exactly went wrong.

In [6]:
# A syntax error indicates that your code is not properly formatted:
a = 2
print(a+3

SyntaxError: incomplete input (495188828.py, line 3)

In [7]:
# A type error indicates that a function received an input of the wrong type adding a string to an integer is not possible
a = '2'
print(a+3)

TypeError: can only concatenate str (not "int") to str

In [5]:
# An index error suggests that it is not possible to index an object in the attempted way.
a = [2, 3]
a[3]

IndexError: list index out of range

You can return errors yourself using the command `raise`:

In [8]:
a = 3
if a == 3:
  raise ValueError('a should not be three')

ValueError: a should not be three

### Exercise
Write a function `integer_add` that takes two arguments and adds them together. If either of the arguments are not integers, it should raise an error. What is the correct error for this issue?

In [9]:
def integer_add (a, b):
    if int==type(a) and int==type(b):
        print(a+b)
    else:
        raise TypeError("both values should be integers")


In [10]:
integer_add(2,3)

5


In [11]:
integer_add(1,2)

3


## Try / Except


`try` tries the code in the `try` codeblock, and if it gives an error, runs code in an `except` code block. Best practice is to specify the errors you expect in the `except` statement so that you don't accidentally allow an unexpected error to go by unreported and unnoticed.

For example, lets say that we want to count the number of occurrences of each letter in a given word -- for this example we will use abracadabra, but we want our code to work on any word.

We might decide to do this using a dictionary where the keys are the letters and the values are the number of times that letter has occurred. We only want to have letters that do occur in the word as keys in our dictionary.

In [12]:
word = "abracadabra"

letter_counts = {
    'a': 0
}
for letter in word: # we can loop through strings like lists or tuples.
  letter_counts[letter]+=1 # add one to the value at key letter

KeyError: 'b'

In [13]:
word = "abracadabra"


letter_counts = {}
for letter in word:
  try:
    letter_counts[letter]+=1
  except KeyError: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

{'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1}


See below for why it is important to specify the type of error you expect. Since we specified the type of error we expected and got a different error, we still find out that there is an error, and can take precautions to make sure we don't, for example, overwrite important info.

In [14]:
word = "abracadabra"


letter_counts = {}
letter_counts['a'] = "important info that should not be overwritten" # something unexpected as a value
for letter in word:
  try:
    letter_counts[letter]+=1
  except KeyError: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

TypeError: can only concatenate str (not "int") to str

What happens if you do not specify KeyError after `except` and just write `except:`?

Try modifying below.

In [15]:
word = "abracadabra"


letter_counts = {}
letter_counts['a'] = "important info that should not be overwritten" # something unexpected as a value
for letter in word:
  try:
    letter_counts[letter]+=1
  except KeyError: # we specify the type of error we expect here
    letter_counts[letter] = 1

print(letter_counts)

TypeError: can only concatenate str (not "int") to str

### Exercise:
Use try/except to write code that takes numbers a and b and prints a/b. If it gets an error (for example b is 0), it should instead print "Cannot divide by zero". Try your code with a few different choices of a and b to make sure it works correctly.

*Hint* To find out what error you should be expecting try dividing something by 0 to see what error you get.

In [20]:
a=2
b=0
try:
    print (a/b)
except:
    print("cannot divide")


cannot divide


# Numpy

We often want to work with arrays of numerical data, for example a list of firing rates. We can store such data using basic Python, more specifically as a list of numbers:

In [21]:
lst_1 = [25, 20, 40, 5] 

But these lists are missing a lot of functionality that we find useful for handling numerical data. (You may be used to these from Matlab or R.) For example, suppose you want to multiply each number by 2. We may want the following command to work:

In [22]:
2*lst_1

[25, 20, 40, 5, 25, 20, 40, 5]

Yet its output is not what we are looking for. This is because lists are not *vectorized*: they do not assume that operations should be applied elementwise. Instead we would have to use a command like the one below:

In [23]:
lst_2 = [lst_1[i]*2 for i in range(4)] #multiply by 2 each element of list 1 for all range of elements which is 4
lst_2

[50, 40, 80, 10]

To address this and other issue that arise in handling numerical data in Python, we can use `numpy`, which stands for numerical data in Python.

So far, we have exclusively used Python's base functionality. `numpy` is the first example of a package that has been contributed by external users and has to be installed manually. It is, however, integral to Python for basically anyone working with numerical data.

In [24]:
import numpy as np

## One-dimensional arrays: Vectors
The central object of interest for numpy is an *array*, which refers to rectangular data (more on this later). The simplest case of an array is a one-dimensional one, a vector. You can create a vector from a list:

In [25]:
vec_1 = np.array(lst_1)  #one dimensional arrays is vectors

In [26]:
vec_1

array([25, 20, 40,  5])

In [27]:
type(vec_1)

numpy.ndarray

We can also turn a vector back into a list:

In [28]:
list(vec_1)

[25, 20, 40, 5]

Using the numpy array, we can now perform mathematical operations in the way we would like (and perhaps expect from e.g. Matlab).

In [29]:
vec_2 = 2*vec_1 #another way to multiply all the elements in the list of this vector elementwise
vec_2

array([50, 40, 80, 10])

In [30]:
vec_1+vec_2 #adding vectors(one dimensional arrays) together, we add element 1 of one list to the element 1 of the other list

array([ 75,  60, 120,  15])

In contrast, what happens if we add two lists?

In [31]:
lst_1 + lst_2 #adding lists together, we simply put all elements together without summing up anything

[25, 20, 40, 5, 50, 40, 80, 10]

### Differences between lists and vectors
Both lists and vectors can be indexed and we can easily transform an array into a list and vice versa. What are some of their differences?
#### Elementwise operations
We have already covered that arrays have elementwise operations whereas lists do not.
#### Each element must have the same type
Lists can consist of elements with different types:

In [32]:
lst_3 = ['a', 5] #list can have elements with different types wheres arrays-vectors cannot
lst_3

['a', 5]

An array, on the other hand, will always have the same data type for each of its elements. If a list with unequal types is converted to an array all its elements are converted to the same data type.

In [33]:
vec_3 = np.array(lst_3)
vec_3

array(['a', '5'], dtype='<U11')

<U21 is the data type corresponding to strings. You usually don't want to rely on this automatic casting functionality and should try to avoid it.

In [34]:
type(vec_3)


numpy.ndarray

How can you print out the type of this vector? Note that `type(vec_3)` gives you the type of the entire object which is a numpy array. Rather you want the type of the individual elements. Try using the autocomplete function to find out.

*Hint* look at what the type information was called above.

In [35]:
vec_1.dtype.name #opou a sto fylladio einai to vec_1


'int32'

We do we not need parentheses after `dtype`? This is because `dtype` is not function, but rather a new type of Python object called an *attribute*. We will get to know them in more depth in a later lesson.

The order of types is:
- object (general Python objects)
- string
- float
- int
- boolean

### Question 1

- Create a numpy array with the elements 3, 7, 10 and divide each element by two
- Create a new array `vec_4` that is the elementwise multiplication of `vec_1` and `vec_2`.
- Create an array `vec_5` that has a `True` value wherever `vec_1` is smaller than or equal to `20` and a `False` value otherwise. *Hint:* This should be possible in a one liner.

In [36]:
numbers=np.array([3,7,10])
numbers/2
vec_4=vec_1*vec_2
print(vec_4)
vec_5 = vec_1<=20
print(vec_5) 


[1250  800 3200   50]
[False  True False  True]


## Two-dimensional arrays: Matrices
Rectangular data in two dimensions is often called a matrix: it consists of observations organized by rows and columns. Basic Python would allow us to store such data using a list of lists:

In [37]:
lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]                                         #they are in a matrix because we don't have only one row. We have rows and columns
lst_1

[[1, 2], [3, 4], [5, 6]]

Yet the already tedious process of computing elementwise operations quickly becomes infeasible in this context. If wanted to multiply each element by two we would have to iterate over the outer list and then the inner set of lists.

In [38]:
lst_2 = [
    [2*it2 for it2 in it] for it in lst_1
]
lst_2            #I ado not understand the concept of it2

[[2, 4], [6, 8], [10, 12]]

Again we can turn the list of lists into a matrix simply by applying `np.array`:

In [39]:
mat_1 = np.array(lst_1)   #we can put the list of lists in a matrix with the same logic we did in a vector, except the matrix is two-dimensional and the vector one-dimensional
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Now we can apply vectorized operations as previously:

In [40]:
mat_2 = 2*mat_1
mat_2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you find out the number of rows and columns of the matrix? Try googling or exploring the methods using the autocomplete function.

In [41]:
mat_1.shape #to find out the rows and columns of matrix so 3 rows and 2 columns

(3, 2)

Importantly, numpy, by default, uses elementwise computations. So `*` results in elementwise multiplication, not matrix multiplication.

In [42]:
mat_1*mat_2   #elementwise multiplications of matrices so for each element separately and not all elements just multiplied together

array([[ 2,  8],
       [18, 32],
       [50, 72]])

You can run matrix multiplication by using the `@` operator.

In [43]:
mat_3 = np.array([[1,2],[3,4]])  #it is as follows: a b  a' b'
mat_1@mat_3                                        #c d  c' d'
                                                # a x a'+ b x c'  #a x b' + b x d'
                                                # c x a' + d x c'  #c x b' + d x d' 

array([[ 7, 10],
       [15, 22],
       [23, 34]])

### Saving arrays
We can save arrays using `np.save`.

In [44]:
np.save('mat_1.npy', mat_1)

In [45]:
mat_1_copy = np.load('mat_1.npy')

In [46]:
mat_1_copy

array([[1, 2],
       [3, 4],
       [5, 6]])

## Higher-dimensional arrays

We now load some simulated data, which is stored in the file `ex_array.npy`. Try assigning the data in that file to the variable `arr`.

In [47]:
arr = np.load('ex_array.npy')

Suppose you know that what is stored in this data are spike rates of fifty different neurons for two different conditions and ten repeated measurements. Spike rates are recorded every second for 2000 seconds. How can you figure out how this data is represented in the array?

In [48]:
arr.shape #2 conditions, 10 repeated measurements, 50 dif neurons, recorded every sec for 2000sec
#here we have higher dimensional arrays that are symbolized as arr

(2, 10, 50, 2000)

In [49]:
arr.ndim  #number of array dimensions   #array has 4 dimensions:first condition, second trial, third neuron, fourth timepoint

4

Whereas a vector has one dimension and a matrix has two dimensions, `arr` has four dimensions: the first one specifies the condition, the second one the trial, the third one the neuron, and the fourth one the timepoint. We can also create higher-dimensional arrays directly:

In [50]:
arr_2 = np.array([                 
    [[2,4,6],
     [1,3,5]],
    [[0.5,1,2],
     [0.75, 1, 1.25]]
])

What is `arr_2.ndim` and `arr_2.shape`?

In [51]:
arr_2.ndim  #number of array dimensions is the number of values inside every bracket

3

In [52]:
arr_2.shape #it is the number of conditions we have, so 2 big brackets, 2 subbrackets and 3 dimensions for each one of the subbrackets

(2, 2, 3)

### Data must be rectangular
Importantly numpy only allows for rectangular data. What happens if you create an array from a list of lists with unequal length?

In [53]:
mat = np.array([[1,2],[3]])

C:\Users\julap\AppData\Local\Temp\ipykernel_40108\2922253680.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mat = np.array([[1,2],[3]])


In [54]:
mat

array([list([1, 2]), list([3])], dtype=object)

### Broadcasting

In general you cannot add two matrices with different shapes:

In [55]:
mat_1.shape   #we cannot add 2 matrices with different shapes

(3, 2)

In [56]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])

In [57]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [58]:
np.array([                                 #
    [1,2]
]) + np.array([
    [1,2],
    [3,4],
    [5,6]
])

array([[2, 4],
       [4, 6],
       [6, 8]])

The same thing is true for matrices with one column or other elementwise operations.

In [59]:
divisor = np.array([[2], [1], [1]])

In [60]:
divisor.shape

(3, 1)

In [61]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
mat_1 / divisor #you divide the mat1 with the divisor elementwise pou to divisor einai 2,1,1

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [63]:
vec_4 = np.array([1, 2]) 

In [64]:
vec_4.shape #me ena bracket opws afto[] mpainei keno

(2,)

In [65]:
vec_4+mat_1

array([[2, 4],
       [4, 6],
       [6, 8]])

### Creating some arrays

In [66]:
np.linspace(0, 1, 21) #21 equally spaced values between 0 and 1)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [67]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [70]:
np.ones((4, 2, 3)) #ones dhladh to 1 se 4 pairs apo 2 sthles me 3 noumera #WHY np.ones?? What does 1 represent?

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 2

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [71]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))

In [72]:
arr_1 = np.ones((3,2)) #3 pairs me 2 times mesa to kathena
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
arr_2 = np.ones((2,3))
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))

In [75]:
arr_1 = np.ones((4,1,5))
np.ones((4,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [76]:
arr_2 = np.ones((4,6,5))
np.ones((4,6,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [77]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))

In [78]:
arr_1 = np.ones((4,1,5))
np.ones((4,1,5))

array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]])

In [79]:
arr_2 = np.ones((4,6,1))
np.ones((4,6,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [80]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))

In [81]:
arr_1 = np.ones((4,3,5))
np.ones((4,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [82]:
arr_2 = np.ones((3,5))
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))

In [85]:
arr_1 = np.ones((4,3,5))
np.ones((4,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [86]:
arr_2 = np.ones((4,3))
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [87]:
arr.mean()

0.8717270073789571

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [99]:
arr.shape

(2, 10, 50, 2000)

In [102]:
arr_across_trials = arr.mean(axis=1) #specify the axis. 10 is gone here because it is the axis 1 (0,1,2,3)

In [103]:
arr_across_trials.shape

(2, 50, 2000)

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [104]:
arr_across_trials = arr.mean(axis=1, keepdims=True)  #you set the repeated times to just 1???

In [105]:
arr_across_trials.shape #number of all conditions we have among trials

(2, 1, 50, 2000)

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [106]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [107]:
arr_across_trials_and_time.shape

(2, 50)

### Question 3

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

In [111]:
arr_across_trials_and_neurons_and_times=arr.mean(axis=0)  #is that correct??

arr_across_trials_and_neurons_and_times.shape

(10, 50, 2000)

## Indexing

Indexing in vectors works just as in lists:

In [93]:
vec_1

array([25, 20, 40,  5])

In [94]:
vec_1[0]

25

For matrices and higher-dimensional arrays, a single index selects a single row:

In [95]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
mat_1[0]

array([1, 2])

In [96]:
mat_1[0][1] #o arithmos 2 giati exoume mazi 0 k 1 opote to 0 einai to1 k to 1 to 2

2

Instead of using two brackets, you can also separate the row and column index by a comma:

In [ ]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

In [97]:
print(mat_1[0][0])

1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [80]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [82]:
vec[:7]  #apo to 0 mexri to 6 otan vazeis : mprosta

array([0, 1, 2, 3, 4, 5, 6])

In [83]:
vec[3:]  #apo to 3 mexri to telos

array([3, 4, 5, 6, 7, 8, 9])

In [84]:
vec[:] # What do you think this will do? #all of it

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [100]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
mat_1[:,0]  #ksekiname apo thn arxh k vasika einai h prwth timh k gia tis 3 sthles

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [102]:
vec[3:7:2]

NameError: name 'vec' is not defined

We could still leave away the beginning or the end of the slice:

In [88]:
vec[::2] #only every second number

array([0, 2, 4, 6, 8])

### Question 4
Predict the output of the following commands:

In [89]:
vec[:4]

array([0, 1, 2, 3])

In [90]:
vec[5:9:2]

array([5, 7])

In [91]:
vec[:7:2]

array([0, 2, 4, 6])

In [92]:
vec[2::2] #from 2 till the end of the list every 2

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [ ]:
vec

In [ ]:
selector = vec <= 5
selector

You can use these boolean arrays to subset the corresponding true values.

In [ ]:
vec

In [ ]:
vec[selector]

In [ ]:
vec[vec<=5]

You can do the same with matrices:

In [ ]:
mat_1

In [ ]:
mat >= 3

In [ ]:
mat[mat >= 3]

### Questions 5
- Consider the example matrix from above and subset all entries with values between 0.4 and 0.8.