In [1]:
import numpy as np
arr = np.load('ex_array.npy')

### Reshaping
Often, we want to arrange an array in a different shape. For this purpose, we can use the `reshape` method.

In [2]:
mat_1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
mat_1.shape

(3, 2)

The simplest example of this is flattening a matrix:

In [4]:
mat_1.reshape(6)

array([1, 2, 3, 4, 5, 6])

This is so popular that there is a special function for it:

In [5]:
mat_1.flatten()

array([1, 2, 3, 4, 5, 6])

In [6]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

As you can see, the `reshape` method iterates through rows before columns. What will be the output of `mat_1.reshape(2,3)`?

In [7]:
mat_3 = mat_1.reshape(2, 3)  #grapse mu ta values me rows kai columns dhladh me 2 rows kai 3 columns afu exume mat_1.reshape(2,3)
mat_3

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
mat_3.shape      #dwse mu ton arithmo twn rows kai twn columns

(2, 3)

## Exercises
1. What will be the output of the following piece of code:
```
vec_1 = np.array([1,2,3,4])
vec_1.reshape(2,2)
```
2. Consider the example array we considered in the lesson (it is loaded into this notebook in the first line together with the numpy import). As a reminder the first two dimensions referred to two different conditions for the neural data and ten repetitions of the measurements. Suppose you didn't care about the differences between those conditions and simply wanted to consider the total of 20 trials as repetitions, thus considering a matrix with 20 repetitions, 50 neurons, and 2000 timesteps. How could you reshape the array in this manner?

In [9]:
#Exercise 1
vec_1=np.array([1,2,3,4])
vec_1

array([1, 2, 3, 4])

In [10]:
#Exercise 1
vec_1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [62]:
#Exercise 2 
import numpy as np
arr = np.load('ex_array.npy')
arr.shape
arr.reshape(20,50,2000)





array([[[0.10673565, 0.85001343, 0.0661262 , ..., 1.22214287,
         1.8543381 , 0.02977156],
        [1.74584281, 1.04634545, 1.19461252, ..., 0.38699475,
         0.1462578 , 0.55766886],
        [1.27660851, 1.63782002, 1.73077654, ..., 0.26917844,
         0.88751874, 0.49740966],
        ...,
        [0.13397769, 0.16198789, 0.4464806 , ..., 0.43995243,
         0.64259425, 1.23527806],
        [2.47564259, 1.69413446, 2.1241746 , ..., 2.61901093,
         3.11246504, 1.92026681],
        [0.7296442 , 2.04679777, 1.37959358, ..., 1.7419921 ,
         2.11039   , 0.89870327]],

       [[0.81078512, 0.93306242, 0.25937912, ..., 1.31543734,
         1.29622586, 1.23752785],
        [0.56674586, 0.78873287, 1.09353632, ..., 0.49521212,
         0.21889655, 0.55503936],
        [0.88290151, 0.68693426, 1.2506505 , ..., 0.9044605 ,
         0.46007422, 0.43821697],
        ...,
        [0.03644922, 0.57104717, 0.49534172, ..., 0.59404023,
         0.28135146, 0.19247644],
        [1.6

## Transposing

`mat_1.T` transposes the matrix flipping rows and columns.

In [29]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
mat_1.T  #flip rows & columns

array([[1, 3, 5],
       [2, 4, 6]])

For higher-dimensional arrays, the `transpose` method allows you to specify the new order of the axes. You are doing so by providing a tuple of integers. If you specify axis 2 in the first entry of that tuple for instance, what used to be axis 2 now becomes axis 0 and so on:

In [31]:
arr.shape

(2, 10, 50, 2000)

In [34]:
arr_t = arr.transpose((2, 0, 1, 3))    #you change the position of the axes
arr_t.shape

(50, 2, 10, 2000)

## Questions
What is going to be the output shape of the following commands?
```
arr_t = arr.transpose((1,3,2,0))
arr_t = arr.transpose((2,1,0,3))
arr_t = arr.transpose((0,1,2,3))
```
Try to predict the shape and then test it by running the commands.

In [35]:
arr_t = arr.transpose((1,3,2,0))
arr_t.shape

(10, 2000, 50, 2)

In [36]:
aarr_t = arr.transpose((2,1,0,3))
arr_t.shape

(10, 2000, 50, 2)

In [37]:
arr_t = arr.transpose((0,1,2,3))
arr_t.shape

(2, 10, 50, 2000)

### Broadcasting

In general you cannot add two matrices with different shapes:

In [38]:
mat_1.shape

(3, 2)

In [39]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])
mat_3.shape

(2, 3)

In [40]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [41]:
mat_4 = np.array([
    [1,2]
])
mat_5 = np.array([
    [1,2],
    [3,4],
    [5,6]
])
mat_4_plus_5 = mat_4+mat_5
mat_4_plus_5

array([[2, 4],
       [4, 6],
       [6, 8]])

In [42]:
mat_4.shape

(1, 2)

In [43]:
mat_5.shape

(3, 2)

The same thing is true for matrices with one column or other elementwise operations.

In [44]:
divisor = np.array([[2], [1], [1]])

In [45]:
divisor.shape

(3, 1)

In [46]:
divisor

array([[2],
       [1],
       [1]])

In [47]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
mat_1 / divisor

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [49]:
vec_1 = np.array([1, 2])  

In [50]:
vec_1.shape

(2,)

In [51]:
mat_1.shape

(3, 2)

In [61]:
vec_1+mat_1   

array([[2, 4],
       [4, 6],
       [6, 8]])

### Questions

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [58]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
#they cannot be together

In [59]:
arr_1.shape

(3, 2)

In [60]:
arr_2.shape

(2, 3)

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))

### Boolean indexing

Do you remember how to create an array that has True values for any entry smaller than 5 and False value for all other entries?

In [ ]:
vec = np.arange(10)

In [ ]:
np.arange(10)

In [ ]:
vec < 5

In [ ]:
selector = vec < 5
selector

You can use these boolean arrays to subset the corresponding true values.

In [ ]:
vec

In [ ]:
vec[selector]

In [ ]:
vec[vec<5]

You can do the same with matrices:

In [ ]:
mat_1

In [ ]:
mat_1 >= 3

In [ ]:
mat_1[mat_1 >= 3]

### Questions
- Consider the example matrix from above and subset all entries with values between 2 and 4.